# Generated by Django 6.0.6 on 2026-06-15 16:40

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('piso', models.SmallIntegerField()),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('precio', models.DecimalField(decimal_places=6, max_digits=12)),
                ('telefono', models.CharField(blank=True, default='1000', max_length=4, null=True)),
                ('descripcion', models.TextField()),
                ('banio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['piso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Desayuno', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, default=datetime.date(2026, 6, 15), null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HabitacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitacioneservicios', to='habitaciones.habitacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitacionservicios', to='habitaciones.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='servicios',
            field=models.ManyToManyField(related_name='habitaciones', through='habitaciones.HabitacionServicio', to='habitaciones.servicio'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='habitaciones.tipo'),
        ),
    ]
