# Generated by Django 6.0.6 on 2026-06-15 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(default=django.utils.timezone.now)),
                ('habitaciones', models.ManyToManyField(related_name='reservas', to='habitaciones.habitacion')),
                ('huspedes', models.ManyToManyField(related_name='reservas', to='cuentas.huesped')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('efectivo', 'EFECTIVO'), ('qr', 'QR'), ('tarjeta', 'TARJETA DEBITO/CREDITO'), ('transferencia', 'TRANSFENCIA')], default='efectivo', max_length=25)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.reserva')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
